//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4927
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace magicAnime.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string captureFolder {
            get {
                return ((string)(this["captureFolder"]));
            }
            set {
                this["captureFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int captureMergin {
            get {
                return ((int)(this["captureMergin"]));
            }
            set {
                this["captureMergin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string encoderFolder {
            get {
                return ((string)(this["encoderFolder"]));
            }
            set {
                this["encoderFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string encodedFolder {
            get {
                return ((string)(this["encodedFolder"]));
            }
            set {
                this["encodedFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool captureSubDir {
            get {
                return ((bool)(this["captureSubDir"]));
            }
            set {
                this["captureSubDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int captureExtension {
            get {
                return ((int)(this["captureExtension"]));
            }
            set {
                this["captureExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoUpdate {
            get {
                return ((bool)(this["autoUpdate"]));
            }
            set {
                this["autoUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool prohibitUpdateWhileRecording {
            get {
                return ((bool)(this["prohibitUpdateWhileRecording"]));
            }
            set {
                this["prohibitUpdateWhileRecording"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool removeSourceWhenEncoded {
            get {
                return ((bool)(this["removeSourceWhenEncoded"]));
            }
            set {
                this["removeSourceWhenEncoded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string saveFolder {
            get {
                return ((string)(this["saveFolder"]));
            }
            set {
                this["saveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool classificatePrograms {
            get {
                return ((bool)(this["classificatePrograms"]));
            }
            set {
                this["classificatePrograms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:0} 第{1:00}話 「{2:0}」")]
        public string saveNameFormat {
            get {
                return ((string)(this["saveNameFormat"]));
            }
            set {
                this["saveNameFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int scheduleFirstHour {
            get {
                return ((int)(this["scheduleFirstHour"]));
            }
            set {
                this["scheduleFirstHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int scheduleTimeZone {
            get {
                return ((int)(this["scheduleTimeZone"]));
            }
            set {
                this["scheduleTimeZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool scheduleEncodeEveryday {
            get {
                return ((bool)(this["scheduleEncodeEveryday"]));
            }
            set {
                this["scheduleEncodeEveryday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int scheduleEncodeTime {
            get {
                return ((int)(this["scheduleEncodeTime"]));
            }
            set {
                this["scheduleEncodeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoShutdownAtEncoded {
            get {
                return ((bool)(this["autoShutdownAtEncoded"]));
            }
            set {
                this["autoShutdownAtEncoded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int autoShutdownType {
            get {
                return ((int)(this["autoShutdownType"]));
            }
            set {
                this["autoShutdownType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minimizeAtStartup {
            get {
                return ((bool)(this["minimizeAtStartup"]));
            }
            set {
                this["minimizeAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minimizeAtPlayer {
            get {
                return ((bool)(this["minimizeAtPlayer"]));
            }
            set {
                this["minimizeAtPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cal.syoboi.jp/list.php")]
        public string syoboiTitleList {
            get {
                return ((string)(this["syoboiTitleList"]));
            }
            set {
                this["syoboiTitleList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cal.syoboi.jp/tid/")]
        public string syoboiTid {
            get {
                return ((string)(this["syoboiTid"]));
            }
            set {
                this["syoboiTid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int reserveStart {
            get {
                return ((int)(this["reserveStart"]));
            }
            set {
                this["reserveStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int reserveEnd {
            get {
                return ((int)(this["reserveEnd"]));
            }
            set {
                this["reserveEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public uint bootupTimeUnification {
            get {
                return ((uint)(this["bootupTimeUnification"]));
            }
            set {
                this["bootupTimeUnification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoPowerManagement {
            get {
                return ((bool)(this["autoPowerManagement"]));
            }
            set {
                this["autoPowerManagement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint shutdownMethod {
            get {
                return ((uint)(this["shutdownMethod"]));
            }
            set {
                this["shutdownMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint bootupHasten {
            get {
                return ((uint)(this["bootupHasten"]));
            }
            set {
                this["bootupHasten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint shutdownPutoff {
            get {
                return ((uint)(this["shutdownPutoff"]));
            }
            set {
                this["shutdownPutoff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string schedulerType {
            get {
                return ((string)(this["schedulerType"]));
            }
            set {
                this["schedulerType"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://members2.jcom.home.ne.jp/kurusugawa/mAgicAnime/")]
        public string helpUrl {
            get {
                return ((string)(this["helpUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoRefresh {
            get {
                return ((bool)(this["autoRefresh"]));
            }
            set {
                this["autoRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int autoRefreshMinute {
            get {
                return ((int)(this["autoRefreshMinute"]));
            }
            set {
                this["autoRefreshMinute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool inTaskTray {
            get {
                return ((bool)(this["inTaskTray"]));
            }
            set {
                this["inTaskTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstRun {
            get {
                return ((bool)(this["firstRun"]));
            }
            set {
                this["firstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cal.syoboi.jp/rss.php")]
        public string syoboiRss {
            get {
                return ((string)(this["syoboiRss"]));
            }
            set {
                this["syoboiRss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cal.syoboi.jp/proginfo.xml")]
        public string syoboiProg {
            get {
                return ((string)(this["syoboiProg"]));
            }
            set {
                this["syoboiProg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hideRefreshDialog {
            get {
                return ((bool)(this["hideRefreshDialog"]));
            }
            set {
                this["hideRefreshDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool notifyUnreadBalloon {
            get {
                return ((bool)(this["notifyUnreadBalloon"]));
            }
            set {
                this["notifyUnreadBalloon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int dayPast {
            get {
                return ((int)(this["dayPast"]));
            }
            set {
                this["dayPast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int dayFuture {
            get {
                return ((int)(this["dayFuture"]));
            }
            set {
                this["dayFuture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int weekPast {
            get {
                return ((int)(this["weekPast"]));
            }
            set {
                this["weekPast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int weekFuture {
            get {
                return ((int)(this["weekFuture"]));
            }
            set {
                this["weekFuture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int viewMode {
            get {
                return ((int)(this["viewMode"]));
            }
            set {
                this["viewMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int calenderMode {
            get {
                return ((int)(this["calenderMode"]));
            }
            set {
                this["calenderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
// <MOD> 2010/01/18 ->
        public IdentifyFileMethod specifiedFile {
            get {
                return ((IdentifyFileMethod)(this["specifiedFile"]));
            }
            set {
                this["specifiedFile"] = value;
            }
        }
//        public int specifiedFile {
//            get {
//                return ((int)(this["specifiedFile"]));
//            }
//            set {
//                this["specifiedFile"] = value;
//            }
//        }
// <MOD> 2010/01/18 <-
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A{0:0}_{1:0}")]
        public string specifiedNameFormat {
            get {
                return ((string)(this["specifiedNameFormat"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int thumbnailWidth {
            get {
                return ((int)(this["thumbnailWidth"]));
            }
            set {
                this["thumbnailWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int thumbnailHeight {
            get {
                return ((int)(this["thumbnailHeight"]));
            }
            set {
                this["thumbnailHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool thumbnailSubtitle {
            get {
                return ((bool)(this["thumbnailSubtitle"]));
            }
            set {
                this["thumbnailSubtitle"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int thumbnailWhitebar {
            get {
                return ((int)(this["thumbnailWhitebar"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int thumbnailSecond {
            get {
                return ((int)(this["thumbnailSecond"]));
            }
            set {
                this["thumbnailSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int thumbnailSize {
            get {
                return ((int)(this["thumbnailSize"]));
            }
            set {
                this["thumbnailSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int updateInterval {
            get {
                return ((int)(this["updateInterval"]));
            }
            set {
                this["updateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool forbiddenThumbnail {
            get {
                return ((bool)(this["forbiddenThumbnail"]));
            }
            set {
                this["forbiddenThumbnail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bootRefresh {
            get {
                return ((bool)(this["bootRefresh"]));
            }
            set {
                this["bootRefresh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ignoreExist {
            get {
                return ((bool)(this["ignoreExist"]));
            }
            set {
                this["ignoreExist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool copyWithOthers {
            get {
                return ((bool)(this["copyWithOthers"]));
            }
            set {
                this["copyWithOthers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool removeSubdir {
            get {
                return ((bool)(this["removeSubdir"]));
            }
            set {
                this["removeSubdir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoTransferAtBoot {
            get {
                return ((bool)(this["autoTransferAtBoot"]));
            }
            set {
                this["autoTransferAtBoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoTransferAtAfterRecord {
            get {
                return ((bool)(this["autoTransferAtAfterRecord"]));
            }
            set {
                this["autoTransferAtAfterRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int autoTransferTime {
            get {
                return ((int)(this["autoTransferTime"]));
            }
            set {
                this["autoTransferTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int hoursPerDay {
            get {
                return ((int)(this["hoursPerDay"]));
            }
            set {
                this["hoursPerDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Rectangle rectWindow {
            get {
                return ((global::System.Drawing.Rectangle)(this["rectWindow"]));
            }
            set {
                this["rectWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool maximizeWindow {
            get {
                return ((bool)(this["maximizeWindow"]));
            }
            set {
                this["maximizeWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".mpg")]
        public string strExtension {
            get {
                return ((string)(this["strExtension"]));
            }
            set {
                this["strExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoMoveWithoutFirstEpisode {
            get {
                return ((bool)(this["autoMoveWithoutFirstEpisode"]));
            }
            set {
                this["autoMoveWithoutFirstEpisode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int reserveDays {
            get {
                return ((int)(this["reserveDays"]));
            }
            set {
                this["reserveDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoEncodeInAfterRecord {
            get {
                return ((bool)(this["autoEncodeInAfterRecord"]));
            }
            set {
                this["autoEncodeInAfterRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int autoEncodeMergin {
            get {
                return ((int)(this["autoEncodeMergin"]));
            }
            set {
                this["autoEncodeMergin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showSoonBalloon {
            get {
                return ((bool)(this["showSoonBalloon"]));
            }
            set {
                this["showSoonBalloon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int timeSoonBalloon {
            get {
                return ((int)(this["timeSoonBalloon"]));
            }
            set {
                this["timeSoonBalloon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int concurrentNums {
            get {
                return ((int)(this["concurrentNums"]));
            }
            set {
                this["concurrentNums"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool makeThumbnailAfterEncode {
            get {
                return ((bool)(this["makeThumbnailAfterEncode"]));
            }
            set {
                this["makeThumbnailAfterEncode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public long startupWait {
            get {
                return ((long)(this["startupWait"]));
            }
            set {
                this["startupWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MigrateVer1900 {
            get {
                return ((bool)(this["MigrateVer1900"]));
            }
            set {
                this["MigrateVer1900"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dontBeginEncodeLessThanMinutes {
            get {
                return ((bool)(this["dontBeginEncodeLessThanMinutes"]));
            }
            set {
                this["dontBeginEncodeLessThanMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int maxDelayTimeDontBeginEncode {
            get {
                return ((int)(this["maxDelayTimeDontBeginEncode"]));
            }
            set {
                this["maxDelayTimeDontBeginEncode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoBootup {
            get {
                return ((bool)(this["autoBootup"]));
            }
            set {
                this["autoBootup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool autoShutdown {
            get {
                return ((bool)(this["autoShutdown"]));
            }
            set {
                this["autoShutdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("noAutoReserve")]
        public ReserveControl reserveControl {
            get {
				return ((ReserveControl)(this["reserveControl"]));
            }
            set {
                this["reserveControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int reserveImmediatlyBeforeMinutes {
            get {
                return ((int)(this["reserveImmediatlyBeforeMinutes"]));
            }
            set {
                this["reserveImmediatlyBeforeMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int autoBootNDays {
            get {
                return ((int)(this["autoBootNDays"]));
            }
            set {
                this["autoBootNDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ExternalToolsSetting externalTools {
            get {
				return ((ExternalToolsSetting)(this["externalTools"]));
            }
            set {
                this["externalTools"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int overlapThreshould {
            get {
				return ((int)(this["overlapThreshould"]));
            }
            set {
                this["overlapThreshould"] = value;
            }
        }

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool enablePriority
		{
			get
			{
				return ((bool)(this["enablePriority"]));
			}
			set
			{
				this["enablePriority"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("5")]
		public int overlapMargin
		{
			get
			{
				return ((int)(this["overlapMargin"]));
			}
			set
			{
				this["overlapMargin"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool thumbnailMode
		{
			get
			{
				return (bool)this["ThumbnailMode"];
			}
			set
			{
				this["ThumbnailMode"] = value;
			}
		}

// <ADD> 2010/01/27 ->
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool updateOnAirSoon
		{
			get
			{
				return (bool)this["updateOnAirSoon"];
			}
			set
			{
				this["updateOnAirSoon"] = value;
			}
		}
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("<ArrayOfInt><int>10</int><int>30</int></ArrayOfInt>")]
		public System.Collections.Generic.List<int> untilOnAirMinutes
		{
			get
			{
				return (System.Collections.Generic.List<int>)this["untilOnAirMinutes"];
			}
			set
			{
				this["untilOnAirMinutes"] = value;
			}
		}
// <ADD> 2010/01/27 <-
// <ADD> 2010/01/29 ->
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool showLogPane
		{
			get
			{
				return (bool)this["showLogPane"];
			}
			set
			{
				this["showLogPane"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("100")]
		public int logPaneSize
		{
			get
			{
				return (int)this["logPaneSize"];
			}
			set
			{
				this["logPaneSize"] = value;
			}
		}
// <ADD> 2010/01/29 <-
// <ADD> 2010/01/31 ->
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool disableUnread
		{
			get
			{
				return (bool)this["disableUnread"];
			}
			set
			{
				this["disableUnread"] = value;
			}
		}
// <ADD> 2010/01/31 <-
// <ADD> 2010/04/17 ->
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool keepPlan
		{
			get
			{
				return (bool)this["keepPlan"];
			}
			set
			{
				this["keepPlan"] = value;
			}
		}
// <ADD> 2010/04/17 <-
// <ADD> 2010/04/20 ->
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("2")]
		public int retryDownload
		{
			get
			{
				return (int)this["retryDownload"];
			}
			set
			{
				this["retryDownload"] = value;
			}
		}
// <ADD> 2010/04/20 <-
// <ADD> 2010/08/01 ->
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1")]
		public uint fileTitleMode
		{
			get
			{
				return (uint)this["fileTitleMode"];
			}
			set
			{
				this["fileTitleMode"] = value;
			}
		}
// <ADD> 2010/08/01 <-

	}
}
